### ISSUE TITLE
I annotate my data set into shapenet format. How can I train with your code? I can't find the train.py

### ISSUE THREAD

**Issue by Lizhinwafu** [Biotan/HCFS3D#1]

**Comment by Biotan** [comment]
sorry for losing this file, you can use the train.py now. However, this rep is prepared for S3DIS dataset, you have to revise the code reasonably. Note that we used the super class information as the code of pointnet++ "https://github.com/charlesq34/pointnet2/blob/master/models/pointnet2_part_seg_msg_one_hot.py".

**Comment by Biotan** [comment]
Sorry for losing this file, you can use the train.py now. However, this rep is prepared for S3DIS dataset, you have to revise the code reasonably. Note that we used the super class information as the code of pointnet++ "https://github.com/charlesq34/pointnet2/blob/master/models/pointnet2_part_seg_msg_one_hot.py".

**Comment by Lizhinwafu** [comment]
> Sorry for losing this file, you can use the train.py now. However, this rep is prepared for S3DIS dataset, you have to revise the code reasonably. Note that we used the super class information as the code of pointnet++ "https://github.com/charlesq34/pointnet2/blob/master/models/pointnet2_part_seg_msg_one_hot.py".

Thanks very much
